### PR TITLE
Adding JSON capabilities to chef-solo

### PR DESCRIPTION
**Pull request by enzor**

### CODE REVIEW

**Comment by enzor** [comment]
Don't really understand why travis botched this build O.o

**Comment by diamond29** [comment]
Not sure why, but travis seems to be pulling the latest version of rubocop at 0.36. I couldn't get bundler to pull 0.36 on my local machine for some reason. 

Either way, there are changes in rubocop .36 that aren't compatible with the rubocop configuration in this project. I updated them here

#16

**Comment by diamond29** [comment]
At least I thought i fixed it :smile:

**Comment by enzor** [comment]
:smile: :smile_cat: :smile:

**Comment by ianchesal** [comment]
Weird. I'll merge it and work it out here.

**Pull request merged**
